# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The Movie Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The Movie Test


   pod 'Alamofire', '~> 4.7'
   pod 'ObjectMapper', '~> 3.3'
   pod 'RxSwift',    '~> 4.0'
   pod 'RxCocoa',    '~> 4.0'
   pod 'AlamofireObjectMapper', '~> 5.0'

  target 'The Movie TestTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'RxBlocking', '~> 4.0'
   pod 'RxTest',     '~> 4.0'
  end

  target 'The Movie TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
